### ISSUE TITLE
Zoek naar eigen actoren

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/actoren_widget#1]
ref https://github.com/OnroerendErfgoed/actoren/issues/55

**Comment by cedrikv** [comment]
![zoek_eigen_actoren](https://cloud.githubusercontent.com/assets/1849458/6593737/81032fc2-c7db-11e4-8ba0-511c377d2401.png)

**Comment by cahytinne** [comment]
Na overleg met Wouter @claeyswo :
* agentschap --> /actoren/wij
* zoeken --> filteringselect (zoekknop weg)
* grid --> naam, voornaam, type, ?email?
* sorteerknop weg want sorteren door op kolom te klikken
* detail overnemen van uitgebreid zoeken
* dubbelklik op grid --> event met volledige actor json
* onder grid selecteer actor link (idem dubbelklik)
* dus select checkbox in de grid

**Comment by cahytinne** [comment]
Ik heb de enkel klik event op id geplaatst ipv op de hele rij. Anders werd er bij het selecteren van een rij telkens de detail pagina geopend.

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/actoren_widget/issues/8
