### ISSUE TITLE
Fout bij koppelen actoren vanuit inventaris

### ISSUE THREAD

**Issue by marchaso** [OnroerendErfgoed/actoren_widget#108]
Zie ook https://github.com/OnroerendErfgoed/actoren/issues/517

Er wordt momenteel een call gedaan van de vorm:

https://actoren.onroerenderfgoed.be/actoren/?omschrijving=marchan&sort(+)

Hetgeen een 400 error geeft.

Dit zou iets moeten worden als https://actoren.onroerenderfgoed.be/actoren/?omschrijving=marchan&sort=+veld_naam

**Comment by claeyswo** [comment]
@koenedaele Waar maak ik ticket voor inventaris aan?

**Comment by cedrikv** [comment]
Heeft volgens mij te maken met:
https://github.com/OnroerendErfgoed/actoren/issues/476

Probleem is dat dit moet gefixed worden in alle projecten die de actorwidget gebruiken, de resource wordt niet in de widget geconfigureerd. Dit is de fix (al ok in proces_notas):
https://github.com/OnroerendErfgoed/proces_notas/commit/844b0d0f24efe432ab54f454f111a4acf9f0a2ef#diff-a8c4586c7e8a496a833c3417a7d00cb1

**Comment by koenedaele** [comment]
Ik sluit deze hier af aangezien dit in alle andere projecten moet gefixed worden.
