### ISSUE TITLE
Fix voor gewijzigde volgorde feed na release feedgen==0.6.0

### ISSUE THREAD

**Issue by kmillet** [OnroerendErfgoed/actoren_widget#110]
Indien hier van toepassing, dus feed aanwezig in project. Anders mag deze direct dicht. Zie https://github.com/OnroerendErfgoed/premieaanvragen/issues/297 voor wat meer achtergrond. De fix die Bart daar heeft toegepast werkt voor alle versies van feedgen dus gewoon overnemen.

**Comment by BartSaelen** [comment]
nvt

**Comment by BartSaelen** [comment]
Ik kan dat hier niet sluiten en die "to estimate" wegdoen blijkbaar

**Comment by cedrikv** [comment]
damn, voorbijgestoken door de wouter
