### ISSUE TITLE
ik kan mijn zoekopdracht niet enteren

### ISSUE THREAD

**Issue by marchaso** [OnroerendErfgoed/actoren_widget#112]
N.a.v. het testen van de applicatie openbare onderzoeken:
Ik kan mijn zoekopdracht niet enteren (zowel in Firefox als in Chrome). Ik moet echt op de knop met het vergrootglas drukken, wat niet erg prettig werkt. 

![actoren](https://user-images.githubusercontent.com/30802714/34213308-0d93f96a-e59f-11e7-91ad-d4e627f7fdb3.png)

**Comment by astridvanhumbeeck** [comment]
Werkt ondertussen wel zo in beide browsers
