### ISSUE TITLE
ik land niet op de gewenste pagina in de actorendatabank

### ISSUE THREAD

**Issue by marchaso** [OnroerendErfgoed/actoren_widget#113]
N.a.v. het testen van de applicatie openbare onderzoeken.
Als ik in de applicatie klik op de knop actor aanmaken, land ik in de actorendatabank op het algemene menu. Daar moet ik nog eens klikken op de knop actor aanmaken. Is het mogelijk om deze stap over te slaan en meteen te landen op het laatste scherm?

![actoren](https://user-images.githubusercontent.com/30802714/34217269-66c4bdf6-e5ab-11e7-907a-5e81c733f3cd.png)
![actoren2](https://user-images.githubusercontent.com/30802714/34217279-6b9f7b72-e5ab-11e7-94c6-6034a9003309.png)
![actoren3](https://user-images.githubusercontent.com/30802714/34217286-6ffb47dc-e5ab-11e7-9b70-f017c6cc1b09.png)

**Comment by cedrikv** [comment]
Dit is een functionaliteit die we in de actoren applicatie zelf moeten toevoegen, heb daar een ticketje aangemaakt.
