### ISSUE TITLE
Indien van toepassing - upgrade naar pyramid-tm 2.2.1

### ISSUE THREAD

**Issue by kmillet** [OnroerendErfgoed/actoren_widget#119]
Naar aanleiding van https://github.com/Pylons/pyramid_tm/issues/67

**Comment by axd1967** [comment]
en https://trac.onroerenderfgoed.be/toepassingen/ticket/1428#comment:7

manueel pyramid-tm upgraden is te riskant als workaround? dan kunnen de mensen tenminste verder?

**Comment by cedrikv** [comment]
foute repo denk ik, dit is frontend widget

**Comment by axd1967** [comment]
https://github.com/OnroerendErfgoed/actoren/issues/683
