### ISSUE TITLE
Adressen in de UI verbergen met een einddatum <= vandaag

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/actoren_widget#141]
Zie de actoren app.
adressen worden niet verwijderd, ze krijgen een einddatum:
![image](https://user-images.githubusercontent.com/1849458/59772594-59322700-92ac-11e9-8b73-397becd81982.png)

Ook controleren of we een delete moeten sturen, of een put met een einddatum om adressen te verwidjeren.

**Comment by claeyswo** [comment]
> Ook controleren of we een delete moeten sturen, of een put met een einddatum om adressen te verwidjeren.

PUT met einddatum
