### ISSUE TITLE
Wat krijgen gebruikers zonder een account op de actorendatabank te zien als ze vanuit een andere toepassing de actorenwidget oproepen?

### ISSUE THREAD

**Issue by marchaso** [OnroerendErfgoed/actoren_widget#147]
Wat krijgen gebruikers zonder een account op de actorendatabank te zien als ze vanuit een andere toepassing de actorenwidget oproepen? Een lijst met enkel de publiek personen die je kan vinden op https://actoren.onroerenderfgoed.be/actoren?pagina=1 of nog iets anders?

**Comment by koenedaele** [comment]
Als ze geen rechten hebben, dan zouden ze dezelfde lijst moeten krijgen die je daar aanhaalt. Merk op dat dat publieke personen, maar ook organisaties en software agents zijn.

**Comment by marchaso** [comment]
Bedankt! Ja, inderdaad ook organisaties en software agents.
