### ISSUE TITLE
Als er geen resultaten gevonden zijn blijft de Grid schijnbaar laden

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/actoren_widget#152]
Ik zoek vanuit de inventaris naar een actor die niet bestaat in de actoren databank. Na het klikken op zoeken blijven de rijen in load modus. Komt uit -> https://github.com/OnroerendErfgoed/inventaris/issues/3409

![afbeelding](https://user-images.githubusercontent.com/1926276/78137364-78f2a000-7425-11ea-8237-46561e657bbe.png)

**Comment by cedrikv** [comment]
Bram, deze widget is de dojo versie. je ticket moet naar inventaris zelf.

**Comment by goessebr** [comment]
check, dan kan ik https://github.com/OnroerendErfgoed/inventaris/issues/3409 hiervoor gebruiken
