### ISSUE TITLE
Nieuwe actor wordt steeds opgeslagen als persoon

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/actoren_widget#153]
De post request:
{"actortype":{"id":"2"},"naam":"HP","emails":[],"telefoons":[],"urls":[]}

https://doc.onroerenderfgoed.be/docs/actoren/service.html#hoofdservices
ipv 'actortype' moet het 'type' zijn.

refs https://github.com/OnroerendErfgoed/postregistratie/issues/682

Daarna ticket maken in alle apps die de actorwidget gebruiken

**Comment by vandaean** [comment]
Toepassingen die gebruik maken van de actoren_widget:

Gecontroleerd:
- post (heeft het probleem)
- beeldbank (in orde, geen mogelijkheid om nieuwe actor aan te maken)

Niet gecontroleerd:
- de processen
- adviezen
- toelatingen archeologie
- meldingen aanvang

De niet gecontroleerde toepassingen ken ik niet zo goed en kan ik niet direct testen. @verdugvi Kun jij eventueel eens kijken of het probleem zich bij deze ook stelt?

**Comment by verdugvi** [comment]
- proces nota's: NOK, actortype nieuwe actor is inderdaad fout: https://test-id.erfgoed.net/actoren/4737 en https://test-id.erfgoed.net/actoren/4738
- proces archeologienota's: NOK, idem als bij nota's (https://test-id.erfgoed.net/actoren/4739)
- proces toevalsvondsten: NOK, idem als bij nota's (https://test-id.erfgoed.net/actoren/4741)
- adviezen: OK, nieuwe actor als organisatie aangemaakt via widget, en is inderdaad ook organisatie: https://test-id.erfgoed.net/actoren/4736
- toelatingen archeologie en meldingen aanvang: Bij de toelatingsaanvragen en meldingen aanvang binnen het archeologieportaal kan je geen actoren aanmaken. Of wat bedoel je hier precies?

Bij openbare onderzoeken en inventaris ga je echt naar beheer van actoren om een nieuwe actor aan te maken, die dan ook correct wordt aangemaakt.

**Comment by vandaean** [comment]
Merci om dit na te kijken! Voor toelatingen archeologie en meldingen aanvang zal dit in orde zijn. Wouter had gewoon laten weten welke toepassingen de actoren widget gebruiken. Dit betekent niet noodzakelijk dat je een nieuwe actor kunt aanmaken.

**Comment by verdugvi** [comment]
OK, dat zal dan achterliggend ergens zijn, want je kan ook geen actoren zoeken via de actorenwidget. Maar zal inderdaad dan wel in orde zijn.
