### ISSUE TITLE
Aanpassen type 'publiek persoon' wordt eigenschap 'zichtbaarheid'

### ISSUE THREAD

**Issue by vandaean** [OnroerendErfgoed/actoren_widget#157]
Type 'publiek persoon' verdwijnt en wordt een eigenschap 'zichtbaarheid' met als waarden 'publiek' of 'privaat'.

https://github.com/OnroerendErfgoed/actoren/issues/839

**Comment by cedrikv** [comment]
+ nakijken of het ook in oerelia/invetaris moet aangepast worden
