### ISSUE TITLE
Ik wil dat mijn cursus meteen op de goede plaats staat

### ISSUE THREAD

**Issue by marchaso** [OnroerendErfgoed/actoren_widget#192]
De gebruikers geven aan dat het handig zou zijn als de cursus meteen in het veld "zoek een actor" zou staan bij het openen van de actorenwidget. Is dit mogelijk?

**Comment by cedrikv** [comment]
zeker. voor welk project is dit juist? want deze actor widget is de oude dojo versie (dus bvb de inventaris gebruikt deze niet meer)

**Comment by marchaso** [comment]
Ah, het ging wel om de actoren popup die in de inventaris verschijnt. Ik dacht dat dat de widget was.

**Comment by cedrikv** [comment]
nee, inventaris werkt niet met dojo widets, best de tickets daar aanmaken. 
we sturen ze wel naar de juiste widget als dat nodig zou zijn, in het algemeen. maar voor de test enzo achteraf is het altijd handig dat het ticket dan in inventaris ook zou staan.

**Comment by marchaso** [comment]
Nieuw ticket aangemaakt: https://github.com/OnroerendErfgoed/inventaris/issues/4781
