### ISSUE TITLE
Uitgebreid zoeken

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/actoren_widget#2]
refs https://github.com/OnroerendErfgoed/actoren/issues/47

**Comment by cedrikv** [comment]
![actorenzoek](https://cloud.githubusercontent.com/assets/1849458/6593935/13a9ac06-c7dd-11e4-843e-b93396296b5f.png)

![actorenzoek_actoren](https://cloud.githubusercontent.com/assets/1849458/6593922/01653088-c7dd-11e4-8aec-a67b54db8b8a.png)
![actorenzoek_vkbo](https://cloud.githubusercontent.com/assets/1849458/6593924/016781e4-c7dd-11e4-81dc-331d99d505de.png)
![actorenzoek_vkbp](https://cloud.githubusercontent.com/assets/1849458/6593923/01660152-c7dd-11e4-81d5-48310e6e83a7.png)

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/actoren_widget/issues/8
https://github.com/OnroerendErfgoed/actoren_widget/issues/18
https://github.com/OnroerendErfgoed/actoren_widget/issues/19
