### ISSUE TITLE
Popup gebruiken voor zoeken en aanmaken van actoren.

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#27]
Cfr. desing van @TOM-VC.

Wanneer ik klik op actoren zou er een popup moeten openen waarin ik kan zoeken an actoren aanmaken.

**Comment by cahytinne** [comment]
We hebben dat inderdaad opgemerkt, maar voor gekozen om geen pop-ups te gebruiken omdat de actor widget op zichzelf al een pop-up is (Dialog) in andere applicaties.
Er zal dan een pop-up in een pop-up verschijnen.
Actoren zoeken en aanmaken wordt momenteel in dezelfde Pop-up weergegeven als de actor widget.

Misschien kan de actor widget niet als pop-up geopend worden, dan kunnen 'de zoek en aanmaak' wel in pop-ups verschijnen?

cc: @taeymma, @cedrikv, @TOM-VC

**Comment by koenedaele** [comment]
De huidige manier van functioneren is in elk geval niet erg intuïtief. Ik heb het even uitgeprobeerd in postregistratie en los van het feit dat er een aantal zaken zijn die niet werken, is het ook niet geheel duidelijk hoe het allemaal zou moeten werken.

Kan @TOM-VC dit eens herbekijken samen met jullie? Ik snap de redenering om geen extra pop-ups in te stellen, maar als ik nu een nieuwe actoren aan het toevoegen ben, ben ik eigenlijk al mijn weg kwijt aangezien ik stukken van de postregistratie correspondenten widget zie samen met stukken van de actoren widget.

**Comment by TOM-VC** [comment]
Scherm update :  Vroegere subtitel is nu titel ,  dus subtitel blok valt weg,  
Scherm is eenvoudiger, compacter en heeft onderaan mogelijkheid om te scrollen  ( vertikaal streepje naast type onderaan pop up scherm )  Buttons toevoegen en annuleren blijven steeds zichtbaar. 

![actoren-post3update](https://cloud.githubusercontent.com/assets/9110224/7455307/328b2938-f27b-11e4-9a6f-a50f714226b9.png)

**Comment by cedrikv** [comment]
is ok nu
