### ISSUE TITLE
actoren bewerken

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/actoren_widget#3]
refs https://github.com/OnroerendErfgoed/actoren/issues/47

**Comment by cedrikv** [comment]
![actoren_aanmaken](https://cloud.githubusercontent.com/assets/1849458/6593947/38cae41e-c7dd-11e4-9186-e49a069d78d9.png)

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/actoren_widget/issues/8
