### ISSUE TITLE
Probleem bij bewerken meerdere adressen bestaande actor

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#35]
![image](https://cloud.githubusercontent.com/assets/1850704/8104234/6edada60-102f-11e5-9b86-1b32a4b9d513.png)

Waneer ik een actor bewerk met een bestaand adres, staat dit adres vooringevuld en niet als een reeds bestaand regeltje. Beetje moeilijk om uit te leggen maar vergelijk het met de email adressen. In bovenstaand voorbeeld worden de reeds bestaande email adressen opgelijst en kan ik 1 toevoegen of het huidige verwijderen. Voor adressen is dit niet het geval. Wegens andere problemen kan ik niet testen wat het resultaat zou zijn van bewaren zonder wijzigingen maar ik vermoed dat in dit geval het adres gewoon verloren gaat.

**Comment by cedrikv** [comment]
lokaal is dit opgelost met db1f4c45a934f899cbcc044f39e2a0796c212ae6, te verifëren op dev
