### ISSUE TITLE
Actor kunnen toevoegen vanuit detail view

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/actoren_widget#41]
Als je de details van een actor bekijkt, kan je de actor momenteel niet 'toevoegen'. Dit kan enkel als je in het grid de actor selecteert (zonder de detail pagina te openen). Dit kan verwarrend zijn voor de gebruiker.

**Comment by taeymma** [comment]
Normaal is na de refactoring van overlaatst de actor  'geselecteerd' in het grid wanneer de details geopend worden. Moet nog even getest worden.
