### ISSUE TITLE
Check voor aanmaak nieuwe actoren

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#44]
Vooraleer een nieuwe actor aan te maken zou er een query moeten gebeuren naar ES die checkt of die actor nog niet bestaat.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

Ik zou voorlopig testen op velden naam, voornaam, email en telefoon. Ik weet niet of adressen veel nut hebben.

Indien dit resultaten oplevert zouden deze aan de gebruiker moeten gepresenteerd worden met eventueel de mogelijkheid een van die te selecteren.

@koenedaele

**Comment by koenedaele** [comment]
We kunnen niet rechtstreeks aan ES vanuit de actoren widget. Om dit deftig te doen hebben we OnroerendErfgoed/actoren#142 nodig.

**Comment by cedrikv** [comment]
Moet dit nog in deze milestone blijven?

**Comment by BartSaelen** [comment]
Die service in Actoren is nog niet klaar, die staat nog wel op de sprintplanning.
Ik zou dit dus voor een volgende release nemen.

**Comment by taeymma** [comment]
Service intussen klaar, maar nu is de vraag hoe dit in de frontend moet worden opgevangen.
Als een gebruiker een nieuwe actor wilt saven wordt dus eerst de service aangesproken om te kijken of er gelijkaardige actoren zijn. Deze kunnen dan in bv selectlijst (of iets dergelijks) worden weergegeven. De makkelijke situatie is wanneer de actor echt een nieuwe actor is. Dan wordt deze gewoon opgeslagen.
Wat moet er nu gebeuren als de gebruiker een bestaande actor kiest? Moet deze bestaande actor dan volledig gemerged worden met de nieuw aangemaakte? Moet er een keuze worden gegeven welke velden eventueel gemerged worden? Of eerder een soort van compare waar je kiest welke van de velden van elke actor worden opgeslagen?

pls advise @koenedaele @cedrikv

**Comment by claeyswo** [comment]
Geen of geen relevant resultaat is inderdaad gewoon nieuw. Verder zou ik de keuze laten aan de gebruiker, neem de bestaande actor over as is of merge volgens [deze](https://github.com/OnroerendErfgoed/actoren/issues/141) methode.

**Comment by claeyswo** [comment]
Over de presentatie hiervan in de UI zou ik eens overleggen met @TOM-VC

**Comment by cedrikv** [comment]
Ik stel volgende flow voor:
- Een gebruiker zit in het 'actor aanmaken' scherm en klikt op save
- Er gebeurt een check in de achtergrond of er gelijkaardige actoren bestaan
- Indien wel, krijgt de gebruiker een melding met een lijst van deze actoren waaruit hij 1 kan kiezen om te mergen (en een mogelijkheid om toch gewoon een nieuwe actor aan te maken)
- Indien hij 1 kiest om te mergen, wordt deze bestaande actor geopend in de beheersinterface in EDIT mode, en met al wijzigingen aangebracht volgens de logica van  [deze](https://github.com/OnroerendErfgoed/actoren/issues/141) methode (tl;dr: enkel de lege velden worden overschreven).
- Eventueel kan de 'actor aanmaken' tab in de beheersinterface nog open blijven zodat de gebruiker zelf kan vergelijken. Of deze wordt automatisch gesloten om verwarring te vermijden.

**Comment by koenedaele** [comment]
Klinkt goed. Misschien eens zo implementeren en dan testen of het goed genoeg werkt? 

Het enige wat ik niet goed kan inschatten is of we niet vaak gaan zitten met een geval waarin er eigenlijk geen merge moet gedaan worden, maar waar gewoon de bestaande gebruiker moet gebruikt worden. Maar ik vermoed dat dat in de praktijk op hetzelfde neerkomt?

**Comment by cedrikv** [comment]
We kunnen in de melding van stap 3 ook een optie toevoegen: 'gebruik deze actor'.
De opties zijn dan:
- Gebruik deze actor zonder hem aan te passen
- Merge deze actor
- Laat mij gerust en maak toch een nieuwe actor aan
maar dan beter verwoord

**Comment by koenedaele** [comment]
* Use it!
* Merge it!
* Fuck it!
