### ISSUE TITLE
naam en voornaam niet-editeerbaar in edit mode

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/actoren_widget#46]
waarom zijn deze velden niet editeerbaar in edit-mode? wat bij typfout in naam?

@koenedaele @claeyswo @maarten-vermeyen

**Comment by koenedaele** [comment]
Ik heb er alvast geen idee van. Ik ga er van uit dat daar een reden voor was. Kent iemand die?

Misschien @cedrikv ?

**Comment by cedrikv** [comment]
Nope, geen idee. Misschien @cahytinne ?

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/actoren/issues/47
@claeyswo 
> Velden die bewerkt moeten kunnen worden zijn actortype (dropdown), straat (autocomplete indien land=België anders vrije tekst), nummer (autocomplete indien land=België anders vrije tekst), postbus, postcode (autocomplete indien land=België anders vrije tekst), gemeente (autocomplete indien land=België anders vrije tekst), land (dropdown), email, telefoon en url.

**Comment by claeyswo** [comment]
Waarschijnlijk over het hoofd gezien, zie ook geen reden waarom dit niet kan.

**Comment by koenedaele** [comment]
Ok, implementeren die hap.
