### ISSUE TITLE
Remove 'credentials' from xhr calls to edit adresses

### ISSUE THREAD

**Issue by JDeVos** [OnroerendErfgoed/actoren_widget#49]
When editing an actor adresses, xhr calls are made withCredentials=true, with only accepts responses that provide a "Access-Control-Allow-Credentials" header and triggers an exception otherwise.
refs: https://github.com/OnroerendErfgoed/postregistratie/issues/292

**Comment by claeyswo** [comment]
There is still one [here](https://github.com/OnroerendErfgoed/actoren_widget/blob/master/controllers/ActorController.js#L123). Can be removed as well.

**Comment by claeyswo** [comment]
Ref #51
