### ISSUE TITLE
Verplichte velden bij aanmaak/bewerk actoren

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#52]
Voorlopig is blijkbaar alles verplicht.

De enige verplichte velden (client side) moeten worden:

- naam

**Comment by cedrikv** [comment]
Zie https://github.com/OnroerendErfgoed/actoren/issues/161

**Comment by claeyswo** [comment]
Ik kan @koenedaele niet bereiken maar ik zou zeggen kiss. Hier ook enkel naam, dan houden we het gelijkaardig aan de backend. Zoals @cedrikv ook opmerkte, als mensen geen gegevens hebben gaat dit er gewoon toe leiden dat ze om het even wat beginnen in te vullen.
