### ISSUE TITLE
Lijst van actoren niet steeds gerefreshed

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#56]
Op dev of test in post:

- bij het toevoegen van correspondenten
- typ iets in de zoekbox
- de lijst wordt gefilterd
- soms verschijnt er "geen resultaten", click op column header doet de resultaten echter wel verschijnen

**Comment by taeymma** [comment]
welke versie van actoren_widget is dit precies? kan dit niet dupliceren in de huidige master.

**Comment by claeyswo** [comment]
56d9c79f6d13aadea5fc8f2c3bc22ea849d97d0f

**Comment by claeyswo** [comment]
Ik zal nog eens herdeployen op dev met huidige master

**Comment by claeyswo** [comment]
Probleem doet zich nog steeds voor. Zoals vorige keer blijkbaar enkel bij zoeken naar Onroerend Erfgoed.
