### ISSUE TITLE
relaties type na PUT

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/actoren_widget#59]
Na de PUT van een actor wordt in de respons het type van een relatie doorsgestuurd als null ipv een dict.
Dit geeft problemen bij het editeren van de actoren in de widget.

**Comment by BartSaelen** [comment]
Dit is een ticket voor actoren? Gelieve daar een ticket aan te maken.

**Comment by taeymma** [comment]
https://github.com/OnroerendErfgoed/actoren/issues/166
