### ISSUE TITLE
Splitsen tel. nr (landcode - nummer)

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/actoren_widget#6]

**Comment by cedrikv** [comment]
inputveld landcode: filteringselect (dus select en free text), met voorgedefineerde lijst van alle buurlanden.
vb +321234545
dus geen nul meer

**Comment by cedrikv** [comment]
Mooi voorbeeld:
http://jackocnr.com/intl-tel-input.html

**Comment by dieuska** [comment]
In de client wordt het telefoonnummer in 2 delen opgesplitst:
Landcode & nummer

Landcode: 
Default staat deze op belgie +32
autofill met de landcodes van belgie + zijn buurlanden
Er mogen ook zelf codes worden ingevuld
Opkuis: Aan client wordt hier niet al teveel gedaan (enkel basic zaken). Verdere preparatie gebeurt aan de backend.

Nummer:
Opkuis: Aan client wordt hier niet al teveel gedaan (enkel basic zaken). Verdere preparatie gebeurt aan de backend.

Landcode en nummer worden aan elkaar geplakt en naar de backend gestuurd, waar deze wordt  geprepareerd en gevalideerd tov de PhoneNumberValidator (zie: https://github.com/OnroerendErfgoed/actoren/issues/44)

**Comment by BartSaelen** [comment]
server side wordt er gesplitst in landcode en nummer
https://github.com/OnroerendErfgoed/actoren/issues/81
