### ISSUE TITLE
Uitbreiden gelijkaardige actoren

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#65]
Voorlopig krijgen we een lijst van mogelijk dezelfde actoren. Nu zien we enkel naam en type hetgeen een beetje weinig is om een beslissing te kunnen nemen. Het zou handig zijn indien we hier iets meer detail kunnen opvragen (rechts-klik?), ik denk dan aan email- en gewonen adressen.

**Comment by cedrikv** [comment]
Is het ok dat we een link voorzien naar de actoren detail pagina (in de publieke frontend van actoren)?
