### ISSUE TITLE
Merge van actoren bevat een fout

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/actoren_widget#66]
Stel dat ik een actor probeer aan te maken Jacobs, Els en er bestaat reeds een actor Jacobs (voornaam niet gekend). Als ik merge lijkt het mij logisch dat niet bestaande of lege velden worden overschreven door de nieuwe gegevens. Dit lijkt niet het geval. Werkt bvb. wel voor mailadressen.

**Comment by taeymma** [comment]
Klopt, dit was geschreven toen nog alle velden verplicht waren. Nu is er extra merge op voornaam.

merge gebeurt nu voor: email, telefoon, adres, urls en voornaam.

**Comment by cedrikv** [comment]
@claeyswo: was het enkel de voornaam die niet correct gemerged werd, of nog andere velden?

**Comment by claeyswo** [comment]
Denk dat het probleem zich enkel kan voordoen bij naam aangezien al de rest samengestelde velden zijn.
